name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          architecture: x64
      - name: Test
        run: go test ./...